server:
  port: 8080
spring:
  cloud: 
   gateway: 
    routes:
    
      - id: catalogevent
        uri: lb://catalogevent/
        predicates:
          - Path=/evento/**
          
      - id: databaseusers
        uri: lb://databaseusers/
        predicates:
          - Path=/user/**
          
      - id: ticket
        uri: lb://ticket/
        predicates:
          - Path=/ticket/**
          
      - id: pasarelapago
        uri: lb://pasarelapago/
        predicates:
          - Path=/pasarelapago/**
