server:
  port: 8080
spring:
  cloud: 
   gateway: 
    routes:
      - id: catalogevent
        uri: lb://catalogevent/
        predicates:
          - Path=/evento/**
      - id: databaseusers
        uri: lb://databaseusers/
        predicates:
          - Path=/user/**
